[project]
name = "jazz-fixed-ready-for-railway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "nicegui>=2.15.0",
    "uvicorn>=0.34.2",
]
